### PR TITLE
Add missed package

### PR DESCRIPTION
**Pull request by smlrrlms**
Add missed package to build dep

### CODE REVIEW

**Comment by freemangordon** [comment]
What error does this fix?

**Comment by smlrrlms** [comment]
Without this package I cannot compile deb package. I'm get error that package maemo-launcher-app doesn't exists.

**Comment by MerlijnWajer** [comment]
Hi @samalero - please look at the `ofono-port` branch. That is the current work and it contains this fix. :-)

**Comment by smlrrlms** [comment]
Ok thanks

**Pull request closed without merging**
